### ISSUE TITLE
Directory Scanning Does not appear to be fucntioning 

### ISSUE THREAD

**Issue by Evan-Sa** [secrary/SSMA#28]
Installed ssma without python errors or conflicts. But when I go for a directory scan it throws back a message that filename argument is required 
~/SSMA$ python3 ssma.py -D ~/Labs-and-samples/wannacry
usage: ssma.py [-h] [-k API_KEY] [-d] [-F FLUSH] [-u UPDATE] [-y YARA]
               [-D DIRECTORY] [-r REPORT] [-t]
               filename
ssma.py: error: the following arguments are required: filename

If I preform just a file scan in that same directory 
I get all the expected out put which you can see a snipet below
I believe this has to do with the filename argument being mandatory in the parser

~/SSMA$ python3 ssma.py  ~/Labs-and-samples/wannacry/24d004a104d4d54034dbcffc2a4b19a11f39008a575aa614ea04703480b1022c

███████╗███████╗███╗   ███╗ █████╗
██╔════╝██╔════╝████╗ ████║██╔══██╗ Simple
███████╗███████╗██╔████╔██║███████║ Static
╚════██║╚════██║██║╚██╔╝██║██╔══██║ Malware
███████║███████║██║ ╚═╝ ██║██║  ██║ Analyzer
╚══════╝╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝

File Details: 
	 File: /home/slipstream/Labs-and-samples/wannacry/24d004a104d4d54034dbcffc2a4b19a11f39008a575aa614ea04703480b1022c
	 Size: 3723264 bytes
	 Type: application/x-dosexec
	 MD5:  db349b97c37d22f5ea1d1841e3c89eb4
	 SHA1: e889544aff85ffaf8b0d0da705105dee7c97fe26
	 ssdeep: 98304:wDqPoBhz1aRxcSUDk36SAEdhvxWa9P593R8yAVp2g3R:wDqPe1Cxcxk3ZAEUadzR8yc4gB
	 Date: Sat Nov 20 04:03:08 2010
	 PE file entropy: 7.964258747283063
	 Very high or very low entropy means that file is compressed or encrypted since truly random data is not common.

**Comment by pielco11** [comment]
When the directory scan option was created, the filename arg was optional. I changed it as positional, so yes it has to do with filename arg.

I'll solve this asap. Thanks for reporing!

**Comment by pielco11** [comment]
Ok, I fixed it. Before the merge, you can try it with [my fork](https://github.com/pielco11/SSMA). To run it `python3 ssma.py -D /path/to/malware .`

Let me know if this fix!

**Comment by Evan-Sa** [comment]
Hello thank you for getting back so quick I am still not seeing a change unfortunately got the same error

~/SSMA$ ./ssma.py  -D /home/slipstream/Labs-and-samples/wannacry
usage: ssma.py [-h] [-k API_KEY] [-d] [-F FLUSH] [-u UPDATE] [-y YARA]
               [-D DIRECTORY] [-r REPORT] [-t]
               filename
ssma.py: error: the following arguments are required: filename

**Comment by pielco11** [comment]
Remember to add a `.` after the path

**Comment by Evan-Sa** [comment]
Thank you missed the period works perfectly now. Keep up the great work

**Comment by pielco11** [comment]
Btw, now you can keep following the main repo and not my fork, since it's updated. Again, thank you for pointing out the error.
